# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMDRunHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='Start time')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('timedelta', models.FloatField(default=0.0, null=True, verbose_name='Time')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('is_success', models.BooleanField(default=False, verbose_name='Is success')),
                ('_result', models.TextField(blank=True, null=True, verbose_name='Command raw result')),
                ('_summary', models.TextField(blank=True, null=True, verbose_name='Command result summary')),
            ],
            options={
                'db_table': 'ops_command_history',
                'get_latest_by': 'date_start',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('_tasks', models.TextField(verbose_name='Tasks')),
                ('pattern', models.CharField(default='{}', max_length=64, verbose_name='Pattern')),
                ('_module', models.CharField(default='', max_length=64, null=True, verbose_name='Module')),
                ('_options', models.CharField(default='', max_length=1024, verbose_name='Options')),
                ('_hosts', models.TextField(blank=True, verbose_name='Hosts')),
                ('run_as_admin', models.BooleanField(default=False, verbose_name='Run as admin')),
                ('run_as', models.CharField(default='', max_length=128, verbose_name='Run as')),
                ('_become', models.CharField(default='', max_length=1024, verbose_name='Become')),
                ('created_by', models.CharField(default='', max_length=64, null=True, verbose_name='Create by')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command', to='ops.Task')),
            ],
            options={
                'db_table': 'ops_command',
                'get_latest_by': 'date_created',
            },
        ),
        migrations.AddField(
            model_name='cmdrunhistory',
            name='command',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='ops.Command'),
        ),
        migrations.AddField(
            model_name='cmdrunhistory',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmdhistory', to='ops.Task'),
        ),
    ]
